name 'Mitchell'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures Mitchell'
long_description 'Installs/Configures Mitchell'
version '0.1.0'
